apiVersion: v1
kind: Service
metadata:
  name: echoheaders-tainted
  labels:
    app: echoheaders-teinted
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders-tainted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders-tainted
  labels:
    app: echoheaders-tainted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoheaders-tainted
  template:
    metadata:
      labels:
        app: echoheaders-tainted
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - echoheaders-tainted
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: echoheaders-tainted
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
      tolerations:
      - key: pool
        operator: Equal
        value: pool1
        effect: NoSchedule 
